config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :poneys do
    resources :bookings, only: [:new, :create]
  end
  patch "bookings/:id/accept", to: "bookings#accept"
  patch "bookings/:id/decline", to: "bookings#decline"
  get "mybookings", to: "bookings#mybookings"
  delete "bookings/:id", to: "bookings#destroy"
  get "myponies", to: "poneys#myponies"
  get "user/signin", to: "user#signin"
  get "user/signin", to: "user#login"
  get "user/signup", to: "user#signup"
  get "user/signup", to: "user#register"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :poney
end

app/models/poney.rb
class Poney < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo

  validates :name, presence: true
  validates :name, length: { minimum: 2, maximum: 20, too_long: "20 characters is the maximum allowed" }
  validates :name, format: { with: /\A[A-Za-z0-9.& ]*\z/, message: "only allows letters" }

  validates :price_per_diem, presence: true
  validates :price_per_diem, numericality: { only_integer: true }
  validates :price_per_diem, numericality: { greater_than: 0 }

  validates :color, presence: true
  validates :color, format: { with: /\A[a-zA-Z]+\z/ }
  validates :color, length: { minimum: 2, maximum: 10 }

  validates :height, presence: true
  validates :height, numericality: { less_than_or_equal: 100 }
  validates :height, numericality: { only_integer: true }
  validates :height, format: { with: /\A\d+\Z/ }

  validates :special_power, presence: true
  validates :special_power, length: { maximum: 50 }

  # validates :description, presence: true
  # validates :description, length: { maximum: 50 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_poney, :find_user, only: %i[new create]

  def new
    @owner = User.find(@poney.user_id)
    @booking = Booking.new
  end

  def create
    @owner = User.find(@poney.user_id)
    @poney = Poney.find(params[:poney_id])
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    if @booking.save
      @booking.status = 'pending'
      redirect_to mybookings_path
    else
      render :new
    end
  end

  def mybookings
    @reservations = Booking.where(user_id: current_user.id)
    @reservationasbooker = Booking.where(user_id: current_user.id)
  end

  def accept
    @booking = Booking.find(Poney.find(params[:id]).user_id)
    @booking.status = "accepted"
  end

  def decline
    @booking = Booking.find(Poney.find(params[:id]).user_id)
    @booking.status = "declined"
  end

  def destroy
    @booking = Booking.find(params[:booking])
    @booking.destroy
    redirect_to booking_path
  end

  #def mybookings
    #@user = current_user
    #@bookings = Booking.where(user_id: @user.id)
  #end


  private

  def find_poney
    @poney = Poney.find(params[:poney_id])
  end

  def find_user
    @user = current_user
  end

  def booking_params
    params.permit(:poney_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/poneys_controller.rb
class PoneysController < ApplicationController
  before_action :find_poney, only: [:show, :edit, :update, :destroy]

  def index
    @poneys = Poney.all
  end

  def new
    @poney = Poney.new
  end

  def show
  end

  def edit
  end

  def create
    @poney = Poney.new(poney_params)
    @poney.user_id = current_user.id
    if @poney.save
      redirect_to poney_path(@poney)
    else
      render :new
    end
  end

  def update
    if @poney.update(poney_params)
      redirect_to @poney
    else
      render :edit
    end
  end

  def myponies
    @myponies = Poney.where(user_id: current_user.id)
  end

  def destroy
    @poney.destroy
  end

  private

  def find_poney
    @poney = Poney.find(params[:id])
  end

  def poney_params
    params.require(:poney).permit(:description, :user_id, :name, :nature, :color, :height, :price_per_diem, :special_power, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/mybookings.html.erb
<p class="indiv-card-title"> My bookings </p>

<div class="list">
<div class="list-item">
  <h2 >As a booker :</h2>
  <%= render partial: 'shared/reservationasbooker', collection: @reservations_as_booker %>
</div>

<div class="list-item">
  <h2 >As an owner :</h2>
  <%= render partial: 'shared/reservationasowner', collection: @reservations_as_owner %>
</div>
</div>

app/views/bookings/new.html.erb
<p class="poney-list">This is the reservation's page for ✨ <%= @poney.name %> ✨ </p>

<div class="reservation-box indiv-card-text">
  <% if @user.id != @poney.user_id %>
    <p>📍<strong> Poney's location :</strong> <%= @owner.address %></p>
    <%# maybe we can add a map here and show the shortest itinerary from user's address to its booking's location %>
  <div class="indiv-card-text">
    <p>🐴 <strong> Poney type:</strong> <%= @poney.nature.capitalize %></p>
    <p>✨<strong> SuperPower:</strong> <%= @poney.special_power.capitalize %></p>
  </div>
</div>
  <div class="confirm-booking">
    <p><strong> Do you want to confirm your booking ?</strong></p>
      <%= simple_form_for @booking, :url => poney_bookings_path  do |f| %>
        <div class="btn-individual btn-flat"><%= f.button :submit, 'Confirm' %></div>
      <% end %>
    <p></p>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoneyrBnB</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Berkshire+Swash&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Berkshire+Swash&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Qwigley&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Metal+Mania&family=New+Rocker&display=swap" rel="stylesheet">


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body >
  <%= render 'shared/navbar'%>
  <% if current_page?(root_path) %>
    <%= render 'shared/banner' %>
  <% end %>
    <div class="container" class ="background" style="display:flex, flex-direction:column;margin-bottom: 120px">
      <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="cards">
  <div class="card-category" id="joli-poney">
    Joli Poney
  </div>

  <div class="card-category" id="gentils-poney">
    Gentils Poney
  </div>

  <div class="card-category" id="poney-eclate">
    Poney Eclaté
  </div>
</div>

app/views/poneys/edit.html.erb
<p class="indiv-card-title"> Modifie moi ce poneeey s'il te dépleeey...</p>

<%= simple_form_for @poney, :url => poney_path, method: :patch do |f| %>
  <%= f.input :name, label: 'Your poney name please', placeholder: 'Please name your cutty poney' %>
  <%= f.input :nature, collection: ['gentil', 'joli', 'éclaté'], include_blank: false %>
  <%= f.input :color, placeholder: 'poney color please' %>
  <%= f.input :price_per_diem, placeholder: 'A number please for rate per day' %>
  <%= f.input :height, placeholder: 'how big is this tiny horse ?' %>
  <%= f.input :description, label: 'please describe the poney' %>
  <%= f.input :special_power, label: 'Special power' %>
  <%= f.input :photo, as: :file, label: "Poney's pic URL" %>
  <div class="btn-individual btn-flat"><%= f.button :submit %></div>
<% end %>

app/views/poneys/index.html.erb
<div >
  <h1 class="poney-title">✨Welcome to PoneyrBnb !✨</h1>
</div>

<div >
 <h3 class=poney-list>Here are all our best ponies 🐴</h3>
</div>

<div class="d-flex justify-content-center">
  <button type="button" class="btn btn-primary btn-lg"><%= link_to "Add a poney", new_poney_path %></button>
</div>


<div class="poney-cards">
  <% @poneys.each do |p| %>
    <%= link_to poney_path(p) do %>
      <div class="poney-card text-decoration-none" style=>
        <div>
          <div class="poney-description-title">📇 <strong> Petit nom:</strong> <%= p.name%></div>
          <div class="poney-description-title">📝 <strong> Description:</strong><%= p.description %></div>
          <div class="poney-description-title">🌟 <strong> SuperPower:</strong><%= p.special_power %></div>
          <div class="poney-description-title">💰 <strong>Combien pour cette bôté? (EUR/Jour)</strong>  <%= p.price_per_diem %></div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/poneys/myponies.html.erb
<p class="indiv-card-title" style="margin-top:30px;">Here are all the Poneys you own :</p>

<div class="poney-cards" style="border:double;border-width:16px;border-color: #e2cfc4;border-radius: 23px;" >
    <% @myponies.each do |p| %>
    <%= link_to poney_path(p) do%>
      <div style="font-size:20px; text-align:center;  margin-top:30px; ">➜ <%= p.name %></p></div>
      <% end %>
    <% end %>
</div>

app/views/poneys/new.html.erb
<p class="indiv-card-title">Bienvenue sur le form de création de Pôtit Poney </p>

<%= simple_form_for @poney, method: :post do |f| %>
  <%= f.input :name, label: 'Your poney name please', error: 'Name is mandatory, please specify one' %>
  <%= f.input :nature, collection: ['gentil', 'joli', 'éclaté'], include_blank: false %>
  <%= f.input :color, placeholder: 'poney color please' %>
  <%= f.input :price_per_diem, placeholder: 'A number please for rate per day' %>
  <%= f.input :height, placeholder: 'how big is this tiny horse ?' %>
  <%= f.input :description, label: 'please describe the poney' %>
  <%= f.input :special_power, label: 'Special power' %>
  <%= f.input :photo, as: :file, label: "Choose your poney's picture" %>
  <div class="btn-individual btn-flat"><%= f.button :submit %></div>
<% end %>

app/views/poneys/show.html.erb
<div class ="individual-card">
  <div>
    <div class="indiv-card-title">
      <p><%= @poney.name %></p>
    </div>

    <div class="indiv-card-text">
      <p>🐴 <%= @poney.name %> is a <%= @poney.nature %> poney.</p>
      <p><%= @poney.description %></p>
      <p>📏 It is <%= @poney.height %> feet tall.</p>



<%= cl_image_tag(@poney.photo.key, alt: "Some picture", height: 300, width: 400) %>


  <%# here is a button that allows a user who is
  NOT the poney's owner to book it and a poney's owner to edit the said poney%>
  <div>
    <img src=<%= @poney.profile_pic_url %> alt="" class="individual-card-img">
    <div class="btn-individual btn-flat">
      <% if current_user.id != @poney.user_id %>
        <%= link_to "Book this poney",  new_poney_booking_path(@poney) %>
      <% else %>
        <%= link_to "Edit this poney",  edit_poney_path(@poney) %>
      <% end %>
  </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" id="banner-image">
  <div>
    <p>For a memorable Party, </p>
    <h1 >RENT A PONEY ! </i></h1>
  </div>
</div>


<!--<a class="btn btn-ghost" href="#">Write a story</a>
<a class="btn btn-flat" href="#">Book now</a>
<a class="btn btn-gradient" href="#">Start now</a> -->

app/views/shared/_cardsgrids.html.erb
<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    Breakfast
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/lunch.jpg)">
    Lunch
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/dinner.jpg)">
    Dinner
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon ">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag("poney.jpeg", alt: "Un poney", width: 300) %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <h1 class="title">PoneyrBnB</h1>

  <div >
    <form novalidate="novalidate" class="simple_form search d-flex align-items-center" action="/" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> </button>
    </form>
  </div>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <% if !user_signed_in? %>
        <ul class="nav-item dropdown" style="padding-top: 12px, list-style-type: none;">
            <a class="nav-word" href="#"><%= link_to "Poneys", poneys_path %></a>
            <a class="dropdown-button" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="fas fa-sign-in-alt"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#"><%= link_to 'Sign in', new_user_session_path  %></a>
            <a class="dropdown-item" href="#"><%= link_to 'Sign up', new_user_registration_path %></a>
          </div>
        </ul>
      <% end %>
      <% if user_signed_in? %>

        <a class="nav-word" href="#">
          <%= link_to "Poneys/", poneys_path %>
        </a>

        <div class="dropdown">
          <%= cl_image_tag current_user.photo.key, alt: "", class: "avatar", role:"button", id:"dropdownMenuLink", data: { toggle:"dropdown" } %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <h6 class="dropdown-header"><%= current_user.email %></h6>
            <%= link_to "Your ponies", myponies_path, class: "dropdown-item" %>
            <%= link_to "Your bookings", mybookings_path, class: "dropdown-item" %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>

      <% end %>
  </div>
</div>

app/views/shared/_reservationasbooker.html.erb
  <div class="reservation-card">

    <div>
      <%= image_tag "#{Poney.find(reservationasbooker.poney_id).profile_pic_url}", alt: "Un poney", class: "reservation-card-img"%>
    </div>

    <div class="reservation-card-title">
      <p>Your reservation with </p>
      <p>✨🌟 <%= Poney.find(reservationasbooker.poney_id).name %> 🌟✨</p>
      <p>This reservation is <%= "#{reservationasbooker.status}" %></p>
    </div>

    <div class="reservation-card-txt">
      <ul>
        <li>The owner's email : <%= User.find(Poney.find(reservationasbooker.poney_id).user_id).email %></li>
        <li>Start Date: tbd</li>
        <li>End Date: tbd</li>
      </ul>
    </div>

  </div>

app/views/shared/_reservationasowner.html.erb
  <%# This is the reservation card as an owner %>
  <div class="reservation-card">

    <div>
      <%= image_tag "#{Poney.find(reservationasowner.poney_id).profile_pic_url}", alt: "Un poney", class: "reservation-card-img"%>
    </div>

    <div class="reservation-card-title">
      Reservation #<%= "#{reservationasowner.id}" %>
      <p>This reservation is <%= "#{reservationasowner.status}" %></p>
    </div>

    <div class="reservation-card-txt">
      <ul>
        <li>Booker's email : <%= User.find(Poney.find(reservationasowner.poney_id).user_id).email %></li>
        <li>Start Date: tbd</li>
        <li>End Date: tbd</li>
        <li>Total price: tbd</li>
      </ul>
    </div>

    <div>
      <%= link_to "Accept", accept_path(reservationasowner), method: :patch %>
      <%= link_to "Decline", decline_path(reservationasowner), method: :patch %>
    </div>

  </div>

app/views/shared/_reservationcard.html.erb
<div class="reservation-card">
  <div>
    <%= image_tag "#{Poney.find(reservationcard.poney_id).profile_pic_url}", alt: "Un poney", class: "reservation-card-img"%>  </div>
  <div class="reservation-card-title">
    <p>Your reservation with </p>
    <p>✨🌟 <%= Poney.find(reservationcard.poney_id).name %> 🌟✨</p>
  </div>
  <div class="reservation-card-txt">
  <ul>
    <li>The owner's email : <%= User.find(Poney.find(reservationcard.poney_id).user_id).email %></li>
    <li>Start Date: tbd</li>
    <li>End Date: tbd</li>
  </ul>
  </div>
  <div class="reservation-card-title">
    <p>Have fun, and don't forget to bring  </p>
    <p>✨🌟 <%= Poney.find(reservationcard.poney_id).name %> 🌟✨ back !</p>
  </div>
</div>